// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	v1 "github.com/fvaiiii/ordering_products/shared/pkg/proto/payment/v1"
)

// Payment is an autogenerated mock type for the Payment type
type Payment struct {
	mock.Mock
}

// PayOrder provides a mock function with given fields: ctx, req
func (_m *Payment) PayOrder(ctx context.Context, req *v1.PaymentRequest) (*v1.PaymentResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 *v1.PaymentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.PaymentRequest) (*v1.PaymentResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.PaymentRequest) *v1.PaymentResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.PaymentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.PaymentRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPayment creates a new instance of Payment. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPayment(t interface {
	mock.TestingT
	Cleanup(func())
}) *Payment {
	mock := &Payment{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
