// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/fvaiiii/ordering_products/order/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// PaymentClient is an autogenerated mock type for the PaymentClient type
type PaymentClient struct {
	mock.Mock
}

// Close provides a mock function with no fields
func (_m *PaymentClient) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PayOrder provides a mock function with given fields: ctx, orderUUID, userUUID, paymentMethod
func (_m *PaymentClient) PayOrder(ctx context.Context, orderUUID string, userUUID string, paymentMethod models.PaymentMethod) (string, error) {
	ret := _m.Called(ctx, orderUUID, userUUID, paymentMethod)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, models.PaymentMethod) (string, error)); ok {
		return rf(ctx, orderUUID, userUUID, paymentMethod)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, models.PaymentMethod) string); ok {
		r0 = rf(ctx, orderUUID, userUUID, paymentMethod)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, models.PaymentMethod) error); ok {
		r1 = rf(ctx, orderUUID, userUUID, paymentMethod)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPaymentClient creates a new instance of PaymentClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentClient {
	mock := &PaymentClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
